### ISSUE TITLE
Can't paste into input

### ISSUE THREAD

**Issue by leahjlou** [CanopyTax/cpr-mask#6]
You can't paste contents of your clipboard into the input. Nothing happens if you try, and the input remains empty.

**Comment by dckesler** [comment]
If what you're trying to paste doesn't work with the pattern then yes. But otherwise you can.

**Comment by dckesler** [comment]
The idea behind this is that you want to be able to strip out non-valid characters from a paste event and have cpr-mask fill in its mask with the valid ones.
So pasting `(801) 777-7777` into a phone number mask would strip out the non-numbers and fill its mask.

**Comment by junca8** [comment]
Fixed with #14
